# Generated by Django 4.2.4 on 2023-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cv_logo_url_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(default='My CV', max_length=30),
        ),
        migrations.AddField(
            model_name='logo',
            name='title',
            field=models.CharField(default='My Logo', max_length=30),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(default='My Urls', max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.FileField(upload_to=''),
        ),
    ]
