# Generated by Django 4.2.4 on 2023-09-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cv_title_logo_title_url_title_alter_cv_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urls',
            new_name='url',
        ),
    ]
