# Generated by Django 4.2.4 on 2023-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='personal',
            name='personal_photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
