# Generated by Django 4.2.4 on 2023-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_personal_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='personal_photo',
            field=models.ImageField(default='ME', upload_to=''),
        ),
    ]
