# Generated by Django 4.2.4 on 2023-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_facts_options_skills_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='desc_for_pic',
            field=models.CharField(default='desktop', max_length=30),
        ),
    ]
