# Generated by Django 4.2.4 on 2023-09-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_skills_desc_for_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='bio',
        ),
    ]
