# Generated by Django 4.2.4 on 2023-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_projects_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('career', models.CharField(max_length=60)),
            ],
        ),
    ]
