# Generated by Django 4.2.4 on 2023-09-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_opinion_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('', 'Inactive')], default='Select status', max_length=100),
        ),
    ]
