# Generated by Django 4.2.4 on 2023-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_opinion_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('', 'Inactive')], default='inactive', max_length=100),
        ),
    ]
